### ISSUE TITLE
A2IPNS for ios has expired

### ISSUE THREAD

**Issue by someonewithsomepower** [bi119aTe5hXk/A2IPNS#9]
ios端 A2IPNS 提示已经过期

**Comment by bi119aTe5hXk** [comment]
TestFlight有效期最大90天
过期可以等待下一周期更新，一般1周左右会提交新版本续期，续期后app自动更新，无需重新操作
TestFlight即便过期也不影响推送接收功能的使用（只是app无法打开，无法查看历史记录）
